kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'git@github.com:naeemarsalan/demo-2.git'
  name: crm-part-one
  namespace: demo-one
  labels:
    app: crm-part-one
    app.kubernetes.io/component: crm-part-one
    app.kubernetes.io/instance: crm-part-one
    app.kubernetes.io/name: crm-part-one
    app.kubernetes.io/part-of: spring-app-part-one
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'crm-part-one:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'git@github.com:naeemarsalan/demo-2.git'
      ref: master
    contextDir: /1-demo
    sourceSecret:
      name: kedy
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: crm-part-one-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: crm-part-one-github-webhook-secret
    - type: ConfigChange
  runPolicy: Serial

