apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      app.openshift.io/vcs-ref: master
      app.openshift.io/vcs-uri: git@github.com:naeemarsalan/demo-2.git
      openshift.io/generated-by: OpenShiftWebConsole
    labels:
      app: crm-part-one
      app.kubernetes.io/component: crm-part-one
      app.kubernetes.io/instance: crm-part-one
      app.kubernetes.io/name: crm-part-one
      app.kubernetes.io/part-of: spring-app-part-one
    name: crm-part-one
    namespace: demo-one
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: crm-part-one:latest
    runPolicy: Serial
    source:
      contextDir: /1-demo
      git:
        ref: master
        uri: git@github.com:naeemarsalan/demo-2.git
      sourceSecret:
        name: kedy
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - generic:
        secretReference:
          name: crm-part-one-generic-webhook-secret
      type: Generic
    - github:
        secretReference:
          name: crm-part-one-github-webhook-secret
      type: GitHub
    - type: ConfigChange
kind: List
metadata:
  resourceVersion: ""
