apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      alpha.image.policy.openshift.io/resolve-names: '*'
      app.openshift.io/route-disabled: "false"
      app.openshift.io/vcs-ref: master
      app.openshift.io/vcs-uri: git@github.com:naeemarsalan/demo-2.git
      deployment.kubernetes.io/revision: "5"
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"crm-part-one:latest","namespace":"demo-one"},"fieldPath":"spec.template.spec.containers[?(@.name==\"crm-part-one\")].image","pause":"false"}]'
      openshift.io/generated-by: OpenShiftWebConsole
    labels:
      app: crm-part-one
      app.kubernetes.io/component: crm-part-one
      app.kubernetes.io/instance: crm-part-one
      app.kubernetes.io/name: crm-part-one
      app.kubernetes.io/part-of: spring-app-part-one
    name: crm-part-one
    namespace: demo-one
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: crm-part-one
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: crm-part-one
          deployment: crm-part-one
      spec:
        containers:
        - env:
          - name: MAPBOX_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                key: key
                name: mapbox-api-key
          image: image-registry.openshift-image-registry.svc:5000/demo-one/crm-part-one@sha256:9b1be305bfa721b1ee3260c1e168ea72a15f1c2652c6987b6c1d0c63d7f3a328
          imagePullPolicy: Always
          name: crm-part-one
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /home/jboss/pdf
            name: pdf
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        volumes:
        - name: pdf
          persistentVolumeClaim:
            claimName: pdf
kind: List
metadata:
  resourceVersion: ""
