apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      app.openshift.io/vcs-ref: master
      app.openshift.io/vcs-uri: git@github.com:naeemarsalan/demo-2.git
      openshift.io/generated-by: OpenShiftWebConsole
    labels:
      app: crm-part-one
      app.kubernetes.io/component: crm-part-one
      app.kubernetes.io/instance: crm-part-one
      app.kubernetes.io/name: crm-part-one
      app.kubernetes.io/part-of: spring-app-part-one
    name: crm-part-one
    namespace: demo-one
  spec:
    lookupPolicy:
      local: false
kind: List
metadata:
  resourceVersion: ""
