apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project.yaml
  - pvc.yaml
  - imagestreams.yaml
  - buildconfigs.yaml
  - deployments.yaml
  - routes.yaml
  - services.yaml

