apiVersion: v1
items:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    labels:
      app: crm-part-one
      app.kubernetes.io/component: crm-part-one
      app.kubernetes.io/instance: crm-part-one
      app.kubernetes.io/name: crm-part-one
      app.kubernetes.io/part-of: spring-app-part-one
    name: crm-part-one
    namespace: demo-one
  spec:
    host: crm-part-one-demo-one.apps.cluster-c7j42.dynamic.redhatworkshops.io
    port:
      targetPort: 8080-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: crm-part-one
      weight: 100
    wildcardPolicy: None
kind: List
metadata:
  resourceVersion: ""
